### ISSUE TITLE
Holesky: Connection from Safe using WalletConnect as cluster owner not working (says Not Authorized)

### ISSUE THREAD

**Issue by sharppanda** [monitorssv/monitorssv#1]
I tried to connect to https://holesky.monitorssv.xyz/monitor from Gnosis safe using cluster owner 0x68E1fF5efF55811613A4dCa4B5E965179db91087, but I see:
```
Not Authorized
You are not a cluster owner and cannot configure monitoring settings.
```
The site says Connected: 0x68E1fF5efF55811613A4dCa4B5E965179db91087
Cluster: https://holesky.monitorssv.xyz/cluster/fccd19a065c3501a534b5ad0aa34f9c6393892289f7722b41c04444a78548d09 has the owner 0x68E1fF5efF55811613A4dCa4B5E965179db91087.

**Comment by monitorssv** [comment]
Hi @sharppanda 

If the cluster owner is a contract address, the EOA address that created the contract will have configuration permissions.

The reason is that the contract cannot sign a signature that the service can directly verify.

Your cluster owner address is 0x68E1fF5efF55811613A4dCa4B5E965179db91087, and the 0x9aF746410192740CbA8B901ADBfa43320693f283 that created the safe contract has configuration permissions. Please try it.

Thanks
